# Generated by Django 5.0.7 on 2024-08-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'The Order is Being Prepared'), (2, 'On the Way')], default=0),
        ),
    ]
