# Generated by Django 5.0.7 on 2024-08-05 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
