# Generated by Django 5.0.7 on 2024-08-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_notification_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
