# Generated by Django 5.0.7 on 2024-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'The Order is Being Prepared'), (2, 'On the Way'), (3, 'The order has been delivered')], default=0),
        ),
    ]
