# Generated by Django 5.0.7 on 2024-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'The Order is Being Prepared'), (2, 'The order has been prepared'), (3, 'On the Way'), (4, 'The order has been delivered')], default=0),
        ),
    ]
