# Generated by Django 5.0.7 on 2024-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
